--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.CLIENTE_PREFERENCIA mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE TABLE ISIS2304A241720.CLIENTE_PREFERENCIA 
(
  ID_PREFERENCIA NUMBER NOT NULL 
, ID_CLIENTE NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_PREFERENCIA_CLIENTE_PK ON ISIS2304A241720.CLIENTE_PREFERENCIA (ID_PREFERENCIA ASC, ID_CLIENTE ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.CLIENTE_PREFERENCIA
ADD CONSTRAINT ID_PREFERENCIA_CLIENTE_PK PRIMARY KEY 
(
  ID_PREFERENCIA 
, ID_CLIENTE 
)
USING INDEX ID_PREFERENCIA_CLIENTE_PK
ENABLE
REM INSERTING into ISIS2304A241720.CLIENTE_PREFERENCIA
SET DEFINE OFF;
Insert into ISIS2304A241720.CLIENTE_PREFERENCIA (ID_PREFERENCIA,ID_CLIENTE) values ('29','2');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_PREFERENCIA_CLIENTE_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_PREFERENCIA_CLIENTE_PK ON ISIS2304A241720.CLIENTE_PREFERENCIA (ID_PREFERENCIA ASC, ID_CLIENTE ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
