--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.ESPECTACULO mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.ESPECTACULO
ADD CONSTRAINT COSTO CHECK 
(costo>0)
ENABLE
ALTER TABLE ISIS2304A241720.ESPECTACULO
ADD CONSTRAINT DURACION CHECK 
(duracion>0)
ENABLECREATE TABLE ISIS2304A241720.ESPECTACULO 
(
  ID_ESPEC NUMBER NOT NULL 
, NOMBRE VARCHAR2(255 BYTE) NOT NULL 
, DURACION NUMBER NOT NULL 
, IDIOMA VARCHAR2(255 BYTE) NOT NULL 
, COSTO NUMBER NOT NULL 
, DESCRIPCION VARCHAR2(255 BYTE) NOT NULL 
, SERVICIO_TRADU CHAR(1 BYTE) NOT NULL 
, PARTICIPACION CHAR(1 BYTE) NOT NULL 
, PUBLICO_OBJETIVO VARCHAR2(255 BYTE) NOT NULL 
, ID_COMPANIA NUMBER NOT NULL 
, ID_OPERARIO NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_ESPEC_PK ON ISIS2304A241720.ESPECTACULO (ID_ESPEC ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.ESPECTACULO
ADD CONSTRAINT ID_ESPEC_PK PRIMARY KEY 
(
  ID_ESPEC 
)
USING INDEX ID_ESPEC_PK
ENABLE
REM INSERTING into ISIS2304A241720.ESPECTACULO
SET DEFINE OFF;
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('1','Espectaculo 1','60','Español','330000','Espectaculo 1 de la compania 1','N','S','Mayores de 18','1','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('4','Espectaculo 4','150','Frances','330000','Espectaculo 4 de la compania 2','S','S','Mayores de 18','2','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('5','Espectaculo 5','80','Español','330000','Espectaculo 5 de la compania 3','N','N','Mayores de 18','3','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('6','Espectaculo 6','100','Ingles','330000','Espectaculo 6 de la compania 3','S','N','Mayores de 18','3','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('7','Espectaculo 7','70','Español','330000','Espectaculo 7 de la compania 4','N','S','Mayores de 18','4','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('8','Espectaculo 8','110','Español','330000','Espectaculo 8 de la compania 4','N','S','Mayores de 18','4','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('2','Espectaculo 2','180','Ingles','330000','Espectaculo 2 de la compania 1','S','N','Mayores de 18','1','4');
Insert into ISIS2304A241720.ESPECTACULO (ID_ESPEC,NOMBRE,DURACION,IDIOMA,COSTO,DESCRIPCION,SERVICIO_TRADU,PARTICIPACION,PUBLICO_OBJETIVO,ID_COMPANIA,ID_OPERARIO) values ('3','Espectaculo 3','120','Español','330000','Espectaculo 3 de la compania 2','N','S','Mayores de 18','2','4');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_ESPEC_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_ESPEC_PK ON ISIS2304A241720.ESPECTACULO (ID_ESPEC ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
