--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.FESTIVAL mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.FESTIVAL
ADD CONSTRAINT FECHA_INICIAL_FESTIVAL CHECK 
(FECHA_INICIAL_FESTIVAL < FECHA_FIN_FESTIVAL)
ENABLECREATE TABLE ISIS2304A241720.FESTIVAL 
(
  ID_FESTIVAL NUMBER NOT NULL 
, FECHA_INICIAL_FESTIVAL VARCHAR2(255 BYTE) NOT NULL 
, FECHA_FIN_FESTIVAL VARCHAR2(255 BYTE) NOT NULL 
, ID_ADMINISTRADOR_FESTIVAL NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_FESTIVAL_PK ON ISIS2304A241720.FESTIVAL (ID_FESTIVAL ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.FESTIVAL
ADD CONSTRAINT ID_FESTIVAL_PK PRIMARY KEY 
(
  ID_FESTIVAL 
)
USING INDEX ID_FESTIVAL_PK
ENABLE
REM INSERTING into ISIS2304A241720.FESTIVAL
SET DEFINE OFF;
Insert into ISIS2304A241720.FESTIVAL (ID_FESTIVAL,FECHA_INICIAL_FESTIVAL,FECHA_FIN_FESTIVAL,ID_ADMINISTRADOR_FESTIVAL) values ('1','01/01/2016','12/31/2018','1');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_FESTIVAL_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_FESTIVAL_PK ON ISIS2304A241720.FESTIVAL (ID_FESTIVAL ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
