--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.LOCALIDAD mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.LOCALIDAD
ADD CONSTRAINT CAPACIDAD CHECK 
(CAPACIDAD>1)
ENABLE
ALTER TABLE ISIS2304A241720.LOCALIDAD
ADD CONSTRAINT CAPACIDAD_NN CHECK 
("CAPACIDAD" IS NOT NULL)
ENABLECREATE TABLE ISIS2304A241720.LOCALIDAD 
(
  ID_LOCALIDAD NUMBER NOT NULL 
, NOMBRE VARCHAR2(255 BYTE) NOT NULL 
, CAPACIDAD NUMBER NOT NULL 
, ID_SITIO NUMBER 
, PRECIO NUMBER 
, SILLA_NUMERADA CHAR(1 BYTE) 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_LOCALIDAD_PK ON ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.LOCALIDAD
ADD CONSTRAINT ID_LOCALIDAD_PK PRIMARY KEY 
(
  ID_LOCALIDAD 
)
USING INDEX ID_LOCALIDAD_PK
ENABLE
REM INSERTING into ISIS2304A241720.LOCALIDAD
SET DEFINE OFF;
Insert into ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD,NOMBRE,CAPACIDAD,ID_SITIO,PRECIO,SILLA_NUMERADA) values ('5','PALCODIAMANTE','5','1','15000','S');
Insert into ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD,NOMBRE,CAPACIDAD,ID_SITIO,PRECIO,SILLA_NUMERADA) values ('1','VIP','20','1','5','S');
Insert into ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD,NOMBRE,CAPACIDAD,ID_SITIO,PRECIO,SILLA_NUMERADA) values ('2','PLATINO','10','1','10','S');
Insert into ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD,NOMBRE,CAPACIDAD,ID_SITIO,PRECIO,SILLA_NUMERADA) values ('3','PALCO','5','1','15','S');
Insert into ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD,NOMBRE,CAPACIDAD,ID_SITIO,PRECIO,SILLA_NUMERADA) values ('4','DIAMANTE','12','28','20','N');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_LOCALIDAD_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_LOCALIDAD_PK ON ISIS2304A241720.LOCALIDAD (ID_LOCALIDAD ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
