--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.PREFERENCIA mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.PREFERENCIA
ADD CONSTRAINT DESCRIPCION_NN CHECK 
("DESCRIPCION" IS NOT NULL)
ENABLE
ALTER TABLE ISIS2304A241720.PREFERENCIA
ADD CONSTRAINT TIPO_PREFERENCIA_NN CHECK 
("TIPO_PREFERENCIA" IS NOT NULL)
ENABLECREATE TABLE ISIS2304A241720.PREFERENCIA 
(
  ID_PREFERENCIA NUMBER NOT NULL 
, TIPO_PREFERENCIA VARCHAR2(255 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(255 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_PREFERENCIA_PK ON ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.PREFERENCIA
ADD CONSTRAINT ID_PREFERENCIA_PK PRIMARY KEY 
(
  ID_PREFERENCIA 
)
USING INDEX ID_PREFERENCIA_PK
ENABLE
REM INSERTING into ISIS2304A241720.PREFERENCIA
SET DEFINE OFF;
Insert into ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA,TIPO_PREFERENCIA,DESCRIPCION) values ('1','mayor de edad','Edad mayor a 60');
Insert into ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA,TIPO_PREFERENCIA,DESCRIPCION) values ('10','menor de edad','bebe');
Insert into ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA,TIPO_PREFERENCIA,DESCRIPCION) values ('20','mayor de edad','Edad mayor a 60');
Insert into ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA,TIPO_PREFERENCIA,DESCRIPCION) values ('29','mayor de edad','Edad mayor a 60');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_PREFERENCIA_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_PREFERENCIA_PK ON ISIS2304A241720.PREFERENCIA (ID_PREFERENCIA ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
