--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.REQUERIMIENTOESPECTACULO mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE TABLE ISIS2304A241720.REQUERIMIENTOESPECTACULO 
(
  ID_ESPECTACULO NUMBER NOT NULL 
, ID_REQUERIMIENTO NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_ESPEC_REQ_PK ON ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO ASC, ID_REQUERIMIENTO ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.REQUERIMIENTOESPECTACULO
ADD CONSTRAINT ID_ESPEC_REQ_PK PRIMARY KEY 
(
  ID_ESPECTACULO 
, ID_REQUERIMIENTO 
)
USING INDEX ID_ESPEC_REQ_PK
ENABLE
REM INSERTING into ISIS2304A241720.REQUERIMIENTOESPECTACULO
SET DEFINE OFF;
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('1','1');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('1','2');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('1','3');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('1','4');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('1','5');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('2','1');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('2','3');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('2','5');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('3','2');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('3','4');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('4','1');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('5','2');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('5','3');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('5','5');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('6','1');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('7','2');
Insert into ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO,ID_REQUERIMIENTO) values ('8','4');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_ESPEC_REQ_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_ESPEC_REQ_PK ON ISIS2304A241720.REQUERIMIENTOESPECTACULO (ID_ESPECTACULO ASC, ID_REQUERIMIENTO ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
