--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.SITIO mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.SITIO
ADD CONSTRAINT CAPACIDAD_CT CHECK 
(CAPACIDAD >1)
ENABLECREATE TABLE ISIS2304A241720.SITIO 
(
  ID_SITIO NUMBER NOT NULL 
, TIPO CHAR(1 BYTE) NOT NULL 
, CAPACIDAD NUMBER NOT NULL 
, HORARIO_DISPONIBILIDAD VARCHAR2(255 BYTE) NOT NULL 
, PROTECCION_ATMOSFERICA CHAR(1 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_SITIO_PK ON ISIS2304A241720.SITIO (ID_SITIO ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.SITIO
ADD CONSTRAINT ID_SITIO_PK PRIMARY KEY 
(
  ID_SITIO 
)
USING INDEX ID_SITIO_PK
ENABLE
REM INSERTING into ISIS2304A241720.SITIO
SET DEFINE OFF;
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('20','A','20','Diurno','S');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('28','A','30','Diurno','S');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('224','A','100','Diurno','S');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('2','C','50','Nocturno','N');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('3','A','100','Diurno','S');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('4','C','80','Diurno','N');
Insert into ISIS2304A241720.SITIO (ID_SITIO,TIPO,CAPACIDAD,HORARIO_DISPONIBILIDAD,PROTECCION_ATMOSFERICA) values ('1','A','40','Diurno','S');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_SITIO_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_SITIO_PK ON ISIS2304A241720.SITIO (ID_SITIO ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
