--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
-- No se ha podido presentar el DDL TABLE para el objeto ISIS2304A241720.USUARIO mientras que DBMS_METADATA intenta utilizar el generador interno.
ALTER TABLE ISIS2304A241720.USUARIO
ADD CONSTRAINT ROL_USER CHECK 
(ROL_USER BETWEEN 0 AND 5)
ENABLECREATE TABLE ISIS2304A241720.USUARIO 
(
  ID_USER NUMBER NOT NULL 
, NOMBRE_USER VARCHAR2(255 BYTE) NOT NULL 
, CORREO_USER VARCHAR2(255 BYTE) NOT NULL 
, ROL_USER NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX ISIS2304A241720.ID_USER_PK ON ISIS2304A241720.USUARIO (ID_USER ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ISIS2304A241720.USUARIO
ADD CONSTRAINT ID_USER_PK PRIMARY KEY 
(
  ID_USER 
)
USING INDEX ID_USER_PK
ENABLE
REM INSERTING into ISIS2304A241720.USUARIO
SET DEFINE OFF;
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('1026300768','Camilo','camilo@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('1234543','Laura','Laura@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('20','prueba','n.maya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('201','prueba','n.maya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('1','Juan Diego Gonzalez','jd.gonzalez@hotmail.com','1');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('2','Natalia Maya','n.maya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('3','Camilo Montenegro','c.montenegro@hotmail.com','3');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('4','Carlos Penaloza','c.penaloza@hotmail.com','4');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('5','Laura Maya','l.maya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('6','Juan Felipe Haya','jf.haya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('7','Maria Lucia Pardo','ml.pardo@hotmail.com','3');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('8','Juan Diego Maya','jd.maya@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('9','Carlos Gonzalez','c.gonzalez@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('10','Laura Penaloza','l.penaloza@hotmail.com','2');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('11','Laura Montenegro','l.montenegro@hotmail.com','3');
Insert into ISIS2304A241720.USUARIO (ID_USER,NOMBRE_USER,CORREO_USER,ROL_USER) values ('12','Laura Gonzalez','l.gonzalez@hotmail.com','3');
-- No se ha podido presentar el DDL INDEX para el objeto ISIS2304A241720.ID_USER_PK mientras que DBMS_METADATA intenta utilizar el generador interno.
CREATE UNIQUE INDEX ISIS2304A241720.ID_USER_PK ON ISIS2304A241720.USUARIO (ID_USER ASC) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
